// GENERATED by capture-app.ts, then hand-tuned to take1's ~18s of real footage.
// take2 capture failed (5KB) -> scene 5 uses the animated stepper, so take2 timecodes are unused.
export const HAS_FOOTAGE = true;
export const SHOTS = {
  take1: { src: "capture/take1.webm", search: [0, 12], results: [0, 12], compare: [5, 17], report: [5, 17] },
  take2: { src: "capture/take2.webm", stepper: [0, 4] },
} as const;
