/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Generate + upload real Box savings reports for the 4 CURATED clusters (which live in
 * twincart-data.ts, not live-clusters.json, so the main box-reports.ts skipped them).
 * Writes id -> shared-link map to src/lib/curated-box-reports.json.
 * Run: bun src/pipeline/box-reports-curated.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { env } from '@/lib/env';
import { CLUSTERS } from '@/lib/twincart-data';

const FOLDER = '385683218231';
const CURATED_IDS = ['stanley-40oz', 'owala-32oz', 'airpods-pro-2', 'floral-midi'];

async function boxToken(): Promise<string> {
  const b = env.box();
  const r = await fetch('https://api.box.com/oauth2/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams([
      ['grant_type', 'client_credentials'],
      ['client_id', b.clientId],
      ['client_secret', b.clientSecret],
      ['box_subject_type', 'enterprise'],
      ['box_subject_id', b.enterpriseId],
    ]),
  });
  const j: any = await r.json();
  if (!j.access_token) throw new Error('Box token failed: ' + JSON.stringify(j).slice(0, 120));
  return j.access_token;
}

function reportHTML(c: any): string {
  const e = c.products.exact, v = c.products.value, b = c.products.budget;
  const row = (p: any, tag: string, color: string) => `
    <tr>
      <td style="padding:10px 14px"><span style="background:${color};color:#fff;font-size:11px;font-weight:700;padding:3px 9px;border-radius:999px">${tag}</span></td>
      <td style="padding:10px 14px">${p.name}</td>
      <td style="padding:10px 14px;color:#6b6e7b">${(p.retailer || '').toUpperCase()}</td>
      <td style="padding:10px 14px;font-weight:700">$${p.price}</td>
      <td style="padding:10px 14px;color:#16a34a;font-weight:700">${p.parity}% twin</td>
      <td style="padding:10px 14px;color:#16a34a;font-weight:700">${p.savingsPct ? p.savingsPct + '% off' : '—'}</td>
    </tr>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>TwinCart Savings Report — ${c.title}</title>
<style>body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#0e0f13;max-width:760px;margin:40px auto;padding:0 24px}
h1{font-size:26px}.tag{color:#16a34a}table{width:100%;border-collapse:collapse;margin:18px 0;font-size:14px}
th{text-align:left;padding:10px 14px;background:#f4f4f7;font-size:12px;color:#6b6e7b}tr{border-top:1px solid #eaeaef}
.verdict{background:#e7f7ec;border-left:4px solid #16a34a;padding:16px 18px;border-radius:8px;font-size:15px;line-height:1.5}
.foot{margin-top:28px;font-size:12px;color:#9a9ca8}.seal{display:inline-block;background:#eaf0fe;color:#2563eb;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:600}</style></head>
<body>
<div style="font-size:13px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#16a34a">TwinCart Savings Report</div>
<h1>${c.title}</h1>
<p style="color:#6b6e7b">Category: ${c.category} · ${c.offers.length} listings aggregated across ${new Set(c.offers.map((o: any) => o.retailer)).size} retailers · up to <b class="tag">${c.maxSavingsPct}% off</b></p>
<table><tr><th>Pick</th><th>Product</th><th>Retailer</th><th>Price</th><th>Parity</th><th>Savings</th></tr>
${row(e, 'EXACT', '#0e0f13')}${row(v, 'VALUE', '#16a34a')}${row(b, 'BUDGET', '#c77e16')}</table>
<div class="verdict"><b>TwinCart's verdict:</b> ${c.verdict}</div>
<p style="margin-top:22px"><span class="seal">✓ AP2-signed checkout mandate · ES256</span> &nbsp; <span class="seal">UCP-conformant</span></p>
<div class="foot">Generated by TwinCart — the cross-marketplace twin-finder. Prices captured at report time; demo data, not affiliated with listed retailers.</div>
</body></html>`;
}

async function upload(token: string, name: string, html: string): Promise<string> {
  const form = new FormData();
  form.append('attributes', JSON.stringify({ name, parent: { id: FOLDER } }));
  form.append('file', new Blob([html], { type: 'text/html' }), name);
  const r = await fetch('https://upload.box.com/api/2.0/files/content', {
    method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: form as any,
  });
  const j: any = await r.json();
  let id: string;
  if (j.entries) id = j.entries[0].id;
  else if (j.code === 'item_name_in_use') {
    id = j.context_info.conflicts[0].id;
    const f2 = new FormData();
    f2.append('file', new Blob([html], { type: 'text/html' }), name);
    await fetch(`https://upload.box.com/api/2.0/files/${id}/content`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: f2 as any });
  } else throw new Error('upload failed: ' + JSON.stringify(j).slice(0, 120));
  const sr = await fetch(`https://api.box.com/2.0/files/${id}`, {
    method: 'PUT', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ shared_link: { access: 'open', permissions: { can_download: true, can_preview: true } } }),
  });
  const sj: any = await sr.json();
  return sj.shared_link?.url ?? '';
}

async function main() {
  const curated = (CLUSTERS as any[]).filter((c) => CURATED_IDS.includes(c.id));
  const token = await boxToken();
  const map: Record<string, string> = {};
  console.log(`Uploading ${curated.length} curated reports to Box folder ${FOLDER}...`);
  for (const c of curated) {
    try {
      const url = await upload(token, `TwinCart_${c.id}_${c.query.replace(/\s+/g, '-')}.html`, reportHTML(c));
      map[c.id] = url;
      console.log(`  ✓ ${c.id} → ${url}`);
    } catch (e) {
      console.warn(`  ✗ ${c.id}: ${String(e).slice(0, 80)}`);
    }
  }
  const path = join(process.cwd(), 'src/lib/curated-box-reports.json');
  writeFileSync(path, JSON.stringify(map, null, 0));
  console.log(`\n✓ ${Object.keys(map).length}/${curated.length} curated reports → curated-box-reports.json`);
}
main().catch((e) => { console.error(e); process.exit(1); });
