/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Box report generator. For each live cluster: render a real HTML savings report,
 * upload to Box (CCG auth), create an open shared link, and write boxReport into live-clusters.json.
 * Run: bun src/pipeline/box-reports.ts
 */
import { readFileSync, writeFileSync, statSync, existsSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { env } from '@/lib/env';

const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

/** Render an HTML string to a real PDF via headless Chrome. Returns the PDF bytes. */
function htmlToPdf(id: string, html: string): Buffer {
  const htmlPath = `/tmp/tc_${id}.html`;
  const pdfPath = `/tmp/tc_${id}.pdf`;
  writeFileSync(htmlPath, html);
  if (existsSync(pdfPath)) unlinkSync(pdfPath);
  const args = ['--headless', '--disable-gpu', '--no-pdf-header-footer', `--print-to-pdf=${pdfPath}`, `file://${htmlPath}`];
  try {
    execFileSync(CHROME, args, { stdio: 'ignore' });
  } catch {
    // older/newer Chrome may need the new headless mode
  }
  if (!existsSync(pdfPath) || statSync(pdfPath).size < 5 * 1024) {
    // retry with --headless=new
    execFileSync(CHROME, ['--headless=new', '--disable-gpu', '--no-pdf-header-footer', `--print-to-pdf=${pdfPath}`, `file://${htmlPath}`], { stdio: 'ignore' });
  }
  if (!existsSync(pdfPath) || statSync(pdfPath).size < 5 * 1024) {
    throw new Error(`PDF render failed/too small for ${id} (${existsSync(pdfPath) ? statSync(pdfPath).size : 0} bytes)`);
  }
  return readFileSync(pdfPath);
}

const FOLDER = process.env.BOX_REPORTS_FOLDER_ID && process.env.BOX_REPORTS_FOLDER_ID !== '0'
  ? process.env.BOX_REPORTS_FOLDER_ID : '385683218231';

async function boxToken(): Promise<string> {
  const b = env.box();
  const r = await fetch('https://api.box.com/oauth2/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams([
      ['grant_type', 'client_credentials'],
      ['client_id', b.clientId],
      ['client_secret', b.clientSecret],
      ['box_subject_type', 'enterprise'],
      ['box_subject_id', b.enterpriseId],
    ]),
  });
  const j: any = await r.json();
  if (!j.access_token) throw new Error('Box token failed: ' + JSON.stringify(j).slice(0, 120));
  return j.access_token;
}

function reportHTML(c: any): string {
  const e = c.products.exact, v = c.products.value, b = c.products.budget;
  const row = (p: any, tag: string, color: string) => `
    <tr>
      <td style="padding:10px 14px"><span style="background:${color};color:#fff;font-size:11px;font-weight:700;padding:3px 9px;border-radius:999px">${tag}</span></td>
      <td style="padding:10px 14px">${p.name}</td>
      <td style="padding:10px 14px;color:#6b6e7b">${(p.retailer || '').toUpperCase()}</td>
      <td style="padding:10px 14px;font-weight:700">$${p.price}</td>
      <td style="padding:10px 14px;color:#16a34a;font-weight:700">${p.parity}% twin</td>
      <td style="padding:10px 14px;color:#16a34a;font-weight:700">${p.savingsPct ? p.savingsPct + '% off' : '—'}</td>
    </tr>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>TwinCart Savings Report — ${c.title}</title>
<style>body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#0e0f13;max-width:760px;margin:40px auto;padding:0 24px}
h1{font-size:26px}.tag{color:#16a34a}table{width:100%;border-collapse:collapse;margin:18px 0;font-size:14px}
th{text-align:left;padding:10px 14px;background:#f4f4f7;font-size:12px;color:#6b6e7b}tr{border-top:1px solid #eaeaef}
.verdict{background:#e7f7ec;border-left:4px solid #16a34a;padding:16px 18px;border-radius:8px;font-size:15px;line-height:1.5}
.foot{margin-top:28px;font-size:12px;color:#9a9ca8}.seal{display:inline-block;background:#eaf0fe;color:#2563eb;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:600}</style></head>
<body>
<div style="font-size:13px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#16a34a">TwinCart Savings Report</div>
<h1>${c.title}</h1>
<p style="color:#6b6e7b">Category: ${c.category} · ${c.offers.length} listings aggregated across ${new Set(c.offers.map((o: any) => o.retailer)).size} retailers · up to <b class="tag">${c.maxSavingsPct}% off</b></p>
<table><tr><th>Pick</th><th>Product</th><th>Retailer</th><th>Price</th><th>Parity</th><th>Savings</th></tr>
${row(e, 'EXACT', '#0e0f13')}${row(v, 'VALUE', '#16a34a')}${row(b, 'BUDGET', '#c77e16')}</table>
<div class="verdict"><b>TwinCart's verdict:</b> ${c.verdict}</div>
<p style="margin-top:22px"><span class="seal">✓ AP2-signed checkout mandate · ES256</span> &nbsp; <span class="seal">UCP-conformant</span></p>
<div class="foot">Generated by TwinCart — the cross-marketplace twin-finder. Prices captured at report time; demo data, not affiliated with listed retailers.</div>
</body></html>`;
}

async function upload(token: string, name: string, pdf: Buffer): Promise<string> {
  const blob = () => new Blob([new Uint8Array(pdf)], { type: 'application/pdf' });
  // delete existing same-name file first (idempotent re-runs)
  const form = new FormData();
  form.append('attributes', JSON.stringify({ name, parent: { id: FOLDER } }));
  form.append('file', blob(), name);
  let r = await fetch('https://upload.box.com/api/2.0/files/content', {
    method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: form as any,
  });
  let j: any = await r.json();
  let id: string;
  if (j.entries) id = j.entries[0].id;
  else if (j.code === 'item_name_in_use') {
    const conflict = j.context_info?.conflicts;
    const existingId = Array.isArray(conflict) ? conflict[0]?.id : conflict?.id;
    if (!existingId) throw new Error('conflict but no id: ' + JSON.stringify(j).slice(0, 200));
    id = existingId;
    // upload new version
    const f2 = new FormData();
    f2.append('file', blob(), name);
    const vr = await fetch(`https://upload.box.com/api/2.0/files/${id}/content`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: f2 as any });
    const vj: any = await vr.json();
    if (vj.entries) id = vj.entries[0].id;
  } else throw new Error('upload failed: ' + JSON.stringify(j).slice(0, 120));
  // open shared link
  const sr = await fetch(`https://api.box.com/2.0/files/${id}`, {
    method: 'PUT', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ shared_link: { access: 'open', permissions: { can_download: true, can_preview: true } } }),
  });
  const sj: any = await sr.json();
  return sj.shared_link?.url ?? '';
}

async function main() {
  const path = join(process.cwd(), 'src/lib/live-clusters.json');
  const clusters = JSON.parse(readFileSync(path, 'utf8'));
  const token = await boxToken();
  console.log(`Uploading ${clusters.length} reports to Box folder ${FOLDER}...`);
  let ok = 0;
  for (const c of clusters) {
    try {
      const pdf = htmlToPdf(c.id, reportHTML(c));
      const url = await upload(token, `TwinCart_${c.id}_${c.query.replace(/\s+/g, '-')}.pdf`, pdf);
      c.boxReport = url;
      ok++;
      console.log(`  ✓ ${c.query} → ${url}`);
    } catch (e) {
      console.warn(`  ✗ ${c.query}: ${String(e).slice(0, 80)}`);
    }
  }
  writeFileSync(path, JSON.stringify(clusters, null, 0));
  console.log(`\n✓ ${ok}/${clusters.length} reports uploaded to Box; boxReport links written to live-clusters.json`);
}
main().catch((e) => { console.error(e); process.exit(1); });
