import { chromium } from "playwright";
import { writeFileSync, mkdirSync, renameSync, readdirSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";

const OUT = join(import.meta.dir, "../remotion/public/capture");
const SHOTS = join(import.meta.dir, "../remotion/src/data/shots.ts");
const BASE = process.env.CAPTURE_URL ?? "http://localhost:3000";
const W = 1920, H = 1080;
const pause = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function take(name: string, steps: (page: any) => Promise<void>) {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({
    viewport: { width: W, height: H }, deviceScaleFactor: 1,
    recordVideo: { dir: OUT, size: { width: W, height: H } },
  });
  const page = await ctx.newPage();
  await page.goto(BASE, { waitUntil: "networkidle" }).catch(() => {});
  await pause(800);
  try { await steps(page); } catch (e) { console.warn(`${name} step warning:`, (e as Error).message); }
  await pause(900);
  await ctx.close();
  await browser.close();
  const webm = readdirSync(OUT).find((f) => f.endsWith(".webm"));
  if (webm) renameSync(join(OUT, webm), join(OUT, `${name}.webm`));
}

const clickIf = async (page: any, rx: RegExp) => {
  const b = page.getByRole("button", { name: rx }).first();
  if (await b.count()) { await b.click().catch(() => {}); return true; }
  // fall back to any element with the text
  const t = page.getByText(rx).first();
  if (await t.count()) { await t.click().catch(() => {}); return true; }
  return false;
};

const main = async () => {
  if (existsSync(OUT)) for (const f of readdirSync(OUT)) if (f.endsWith(".webm")) rmSync(join(OUT, f));
  mkdirSync(OUT, { recursive: true });

  // TAKE 1 — twin-finding journey (feeds scenes 3 & 4)
  await take("take1", async (page) => {
    const search = page.getByPlaceholder(/Search a product/i).first();
    await search.click(); await pause(400);
    await search.fill(""); await search.pressSequentially("robot vacuum", { delay: 85 }); await pause(500);
    await clickIf(page, /Find twins/i);
    await page.waitForTimeout(1800);
    await page.mouse.wheel(0, 500); await pause(1300);
    await page.mouse.wheel(0, 400); await pause(1300);
    await page.mouse.wheel(0, -700); await pause(700);
    await clickIf(page, /Compare/i);
    await page.waitForTimeout(2000);
    await page.mouse.wheel(0, 500); await pause(1600);
    await page.mouse.wheel(0, -300); await pause(600);
    await clickIf(page, /Save (savings )?report/i);
    await page.waitForTimeout(2400);
  });

  // TAKE 2 — MULTI-ITEM basket + simulated agent checkout (feeds scene 5)
  await take("take2", async (page) => {
    const doSearch = async (q: string) => {
      const s = page.getByPlaceholder(/Search a product/i).first();
      await s.click(); await s.fill(""); await s.pressSequentially(q, { delay: 55 }); await pause(300);
      await clickIf(page, /Find twins/i); await page.waitForTimeout(1500);
    };
    const addOne = async () => {
      if (!(await clickIf(page, /Add to cart/i))) await clickIf(page, /^\s*Add\s*$/i);
      await pause(1000);
    };
    await doSearch("robot vacuum"); await addOne();
    await doSearch("massage gun"); await addOne();
    await doSearch("led strip lights"); await addOne();
    // open the basket — shows N items + total savings %
    await clickIf(page, /^\s*Cart\s*$/i); await page.waitForTimeout(2400);
    await page.mouse.wheel(0, 420); await pause(1600);
    await page.mouse.wheel(0, -220); await pause(600);
    // check out the whole basket with the agent -> stepper -> awaiting approval
    await clickIf(page, /Check out all|TwinCart Agent|Prepare (agent )?checkout|Checkout/i);
    await page.waitForTimeout(7000);
  });

  const ok = existsSync(join(OUT, "take1.webm")) && existsSync(join(OUT, "take2.webm"));
  const shots = `// GENERATED by capture-app.ts — timecodes (seconds) into each take. Tune to footage.
export const HAS_FOOTAGE = ${ok};
export const SHOTS = {
  take1: { src: "capture/take1.webm", search: [0, 4], results: [4, 11], compare: [11, 19], report: [19, 26] },
  take2: { src: "capture/take2.webm", stepper: [1.5, 10] },
} as const;
`;
  writeFileSync(SHOTS, shots);
  console.log(`Captured (footage ok: ${ok}) and wrote shots.ts`);
};
main();
